version: "3"

services:
  jeteo-web:
    image: ghcr.io/newbies-workplace/jeteo-web:latest
    restart: unless-stopped
    container_name: jeteo-web
    ports:
      - "80:8080"
    networks:
      - reverse-proxy_global

networks:
  reverse-proxy_global:
    external: true