name: Tests

on: [ push ]

jobs:

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.10.0
      uses: actions/setup-node@v2
      with:
        node-version: '16.10.0'
        cache: 'npm'
    - run: npm ci
    - run: npm test


  lint:
    name: ESLint check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.10.0
      uses: actions/setup-node@v2
      with:
        node-version: '16.10.0'
        cache: 'npm'
    - run: npm ci
    - name: Run linters
      uses: wearerequired/lint-action@v1
      with:
        eslint: true
        eslint_args: '"src/**/*.{ts,tsx}"'
        eslint_dir: '"src/"'
        auto_fix: true


  build:
    name: Webpack build
    needs: [unit-test]
    runs-on: ubuntu-latest

    permissions:
      deployments: write

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.10.0
      uses: actions/setup-node@v2
      with:
        node-version: '16.10.0'
        cache: 'npm'
    - run: npm ci
    - run: npm run build
