name: Tests & Code Quality

on: [push]

jobs:

  setup: 
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.10.0
        uses: actions/setup-node@v2
        with:
          node-version: '16.10.0'
          cache: 'npm'
      - run: npm ci

  lint:
    name: ESLint check
    needs: [setup]

    steps:
      - run: npm run lint

  unit-test:
    name: Unit tests
    needs: [setup]

    steps:
      - run: npm run test

  build:
    name: Webpack build
    needs: [unit-test]

    steps:
      - run: npm run build
